apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  DATABASE_URL: "postgresql+psycopg2://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ .Release.Name }}-postgresql:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.database }}"
